from PySide6.QtCore import Qt
from PySide6.QtWidgets import (
    QHBoxLayout,
    QLineEdit,
    QListWidget,
    QScrollArea,
    QSplitter,
    QVBoxLayout,
    QWidget,
)

from app.ui.widgets import Button, FavoriteButton, label


class VaultTab(QWidget):
    def __init__(self):
        super().__init__()
        layout = QVBoxLayout(self)
        layout.setContentsMargins(16, 16, 16, 16)
        layout.setSpacing(16)
        self.splitter = QSplitter(Qt.Orientation.Horizontal)
        left = QWidget()
        left.setObjectName("servicePanel")
        left.setMinimumWidth(200)
        left_layout = QVBoxLayout(left)
        left_layout.setContentsMargins(14, 16, 14, 16)
        left_layout.addWidget(label("Сервисы", "sectionTitle"))
        self.services = QListWidget()
        self.services.setAccessibleName("Сервисы хранилища")
        left_layout.addWidget(self.services)
        self.add_service = Button("+ Сервис")
        left_layout.addWidget(self.add_service)
        row = QHBoxLayout()
        self.edit_service = Button("Изменить")
        self.delete_service = Button("Удалить")
        row.addWidget(self.edit_service)
        row.addWidget(self.delete_service)
        left_layout.addLayout(row)
        self.splitter.addWidget(left)
        right = QWidget()
        right.setMinimumWidth(620)
        right_layout = QVBoxLayout(right)
        right_layout.setContentsMargins(18, 0, 0, 0)
        right_layout.setSpacing(14)
        search_row = QHBoxLayout()
        self.search = QLineEdit()
        self.search.setPlaceholderText("Поиск: сервис, логин, метка…")
        self.search.setAccessibleName("Поиск по хранилищу")
        self.search.setClearButtonEnabled(True)
        search_row.addWidget(self.search, 1)
        right_layout.addLayout(search_row)
        header = QHBoxLayout()
        self.heading = label("Записи", "sectionTitle")
        header.addWidget(self.heading, 1)
        self.favorites = FavoriteButton()
        self.favorites.setAccessibleName("Только избранные")
        self.favorites.setToolTip("Только избранные")
        header.addWidget(self.favorites)
        self.filter_api = Button("API", role="typeFilter")
        self.filter_account = Button("Аккаунты", role="typeFilter")
        self.filter_other = Button("Другое", role="typeFilter")
        self.filter_api.setProperty("recordKind", "api")
        self.filter_account.setProperty("recordKind", "account")
        self.filter_other.setProperty("recordKind", "other")
        for button in (self.filter_api, self.filter_account, self.filter_other):
            button.setCheckable(True)
            header.addWidget(button)
        self.filter_api.setAccessibleName("Фильтр API")
        self.filter_account.setAccessibleName("Фильтр аккаунтов")
        self.filter_other.setAccessibleName("Фильтр других записей")
        self.add_record = Button("+", role="primaryButton")
        self.add_record.setAccessibleName("Добавить запись")
        self.add_record.setToolTip("Добавить запись")
        self.add_record.ensurePolished()
        self.add_record.setProperty("uiSquareButton", True)
        self.add_record.setFixedWidth(self.add_record.sizeHint().height())
        header.addWidget(self.add_record)
        right_layout.addLayout(header)
        self.scroll = QScrollArea()
        self.scroll.setWidgetResizable(True)
        self.cards_page = QWidget()
        self.cards_layout = QVBoxLayout(self.cards_page)
        self.cards_layout.setContentsMargins(0, 0, 8, 0)
        self.cards_layout.setSpacing(12)
        self.cards_layout.addStretch()
        self.scroll.setWidget(self.cards_page)
        right_layout.addWidget(self.scroll, 1)
        self.splitter.addWidget(right)
        self.splitter.setStretchFactor(1, 1)
        self.splitter.setCollapsible(0, False)
        self.splitter.setCollapsible(1, False)
        layout.addWidget(self.splitter)
